### ISSUE TITLE
JSON

### ISSUE THREAD

**Issue by bricelam** [bricelam/EFCore.SqliteExtensions#4]
Should investigate possible integrations using JSON.NET and the [JSON1 extension](https://www.sqlite.org/json1.html)

May overlap with aspnet/EntityFrameworkCore#4021

**Comment by weitzhandler** [comment]
Might be related or helpful: [Impatient](https://github.com/tuespetre/Impatient).

**Comment by bricelam** [comment]
Tracked by referenced issue.
